---
title: "ggplot 1"
output: github_document
---


```{r}
library(tidyverse)
```

Load in a dataset

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Scatterplot    

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```


you can save ggplots
```{r}

ggp_tmax_tmin =
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

## let's fancy it up

e.g. color, lines, other stuff

```{r}
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .4) + 
  geom_smooth(se = FALSE) + 
  facet_grid(. ~name)
## using name creates a legend too
## geom_smooth creates a line for each name 
## you can use geom_point alpha and alpha = 1 points are solid and 0 is clear
## if you want to have the data gsmooth and geom point spread out more use facet grid
## Facet grid allows you to define multiple plots with x and y defined. name would tell them that you don't want to separate out the rows.
## to turn off color say color = NULL 
```

```{r, echo = FALSE}
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = .4) + 
  geom_smooth(se = FALSE)
## above aes is no longer global bc not at global
## smooth is not going to get the color - name 
```

Let's make on more scatterplot. 

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, size = prcp)) + 
  geom_point(alpha = .4) + 
  facet_grid(. ~ name) + 
  geom_smooth (se = FALSE)

#se is the standard error ~ CI. we remove here, so we put FALSE
```


## use data manipulation as part of this
```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(
    tmax = tmax * (9/5) + 32,
    tmin = tmin * (9/5) + 32
  ) %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

## if you want to do data manipulation, you can do so prior to creating the ggplot

## and you can do that as part of 1 command!
```

## Stacking geoms

```{r}

weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_smooth()

## i.e. you don't need to use geom_point (scatterplot)
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()

## hex is better to demonstrate density. need to install "binhex". alt, use geom_bin_2d()
```


